name: pyinstaller

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else (Linux)
        run: ./scripts/pyinstaller-linux.sh

      - name: Upload release artifact (Linux)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/bapmesim_tk-*-linux"
          # Allow adding artifact to existing release
          allowUpdates: true

  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else (Windows)
        shell: cmd
        run: .\scripts\pyinstaller-windows.bat

      - name: Upload release artifact (Windows)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/bapmesim_tk-*-windows.exe"
          # Allow adding artifact to existing release
          allowUpdates: true

