name: pyinstaller

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    # Needed by release action
    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else
        run: |
          set -e
          cd bapmesim_tk
          pip install -e .
          pip install pyinstaller
          pip uninstall --yes typing
          pyinstaller \
            --hidden-import='PIL._tkinter_finder' \
            --name bapmesim_tk \
            --onefile \
            src/bapmesim_tk/__main__.py 
          set +e

      - name: Make release
        run: |
          set -e
          tagname=$(git describe --tags --abbrev=0)
          cd bapmesim_tk/dist
          mv "bapmesim_tk" "bapmesim_tk-${tagname}"
          set +e

      - name: Upload release artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bapmesim_tk/dist/bapmesim_tk-*"

