name: pyinstaller

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else (Linux)
        run: |
          set -e
          cd bapmesim_tk
          pip install -e .
          pip install pyinstaller
          pip uninstall --yes typing
          pyinstaller \
            --hidden-import='PIL._tkinter_finder' \
            --name bapmesim_tk \
            --onefile \
            src/bapmesim_tk/__main__.py 
          tagname=$(git describe --tags --abbrev=0)
          mv dist/bapmesim_tk "dist/bapmesim_tk-${tagname}-linux"
          set +e

      - name: Upload release artifact (Linux)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bapmesim_tk/dist/bapmesim_tk-*-linux"
          # Allow adding artifact to existing release
          allowUpdates: true

  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up everything else (Windows)
        shell: cmd
        run: |
          cd bapmesim_tk
          pip install -e .
          pip install pyinstaller
          pip uninstall --yes typing
          pyinstaller ^
            --hidden-import=PIL._tkinter_finder ^
            --name bapmesim_tk ^
            --onefile ^
            src/bapmesim_tk/__main__.py
          ren dist\bapmesim_tk.exe "bapmesim_tk-${{ github.ref_name }}-windows.exe"

      - name: Upload release artifact (Windows)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bapmesim_tk/dist/bapmesim_tk-*-windows.exe"
          # Allow adding artifact to existing release
          allowUpdates: true

